# Generated by Django 3.2.18 on 2023-02-21 04:07

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predict',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='predict',
            name='prediction',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Leafblast', 'Leafblast'), ('Brownspot', 'Brownspot'), ('Blight', 'Blight')], max_length=16, null=True),
        ),
    ]
