# Generated by Django 4.1.7 on 2023-02-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_predict_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='confidence',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
